// runtime_buildhouse.js — game-side house builder for AI-generated house
// clusters (tools/housegen). Written for game.js (ES5, three.js r149 UMD).
// NOT yet wired into the game: the integration agent should paste/adapt this
// into game.js near the other building helpers (bldg/shop/stripMall) and load
// houses.js (var HOUSE_CLUSTERS / HOUSE_INSTANCES) before game.js like
// meshychars.js is loaded.
//
// Data contract (houses.js, generated by tools/housegen/mkhouses.js):
//   var HOUSE_CLUSTERS = { id: {
//     tex: {front,side,back,roof,                      // JPEG data-URLs
//           garage,door,trim,gable,concrete},          // v2 tiles (optional)
//     dims: [w,d,h], roofType: 'hip'|'gable'|'flat', roofH,
//     wallColor, trimColor, glassColor,                // trim/glass optional
//     feat: { ... } } };                               // optional depth features
//   var HOUSE_INSTANCES = [ [clusterId, x, z, rotDeg, colorShift], ... ];
//   colorShift: 0 (none) or [hueDeg, satMul, lightMul] — cheap per-instance
//   recolor of the SAME cluster textures (one gray house becomes tan/sage).
//
// feat (all fields optional — old specs without feat build the old flat box):
//   soffit: true                  eave soffit slab + fascia (trim texture)
//   win: { f:[[x,cy,w,h],..],     geometric window units per face; x = 0..1
//          b:[...], l:[...],      fraction along that wall, cy = center height
//          r:[...] }              in meters, w/h in meters
//   door: { x, w, h,              front door unit (x fraction, w/h meters)
//           porch: {d, posts},    porch slab roof w/ square posts + stoop
//           recess: true }        OR pier-recess alcove (no porch roof)
//   garage: { x, w, h, out }      garage-door inset: piers+header protrude
//                                 `out`, door tile recessed at wall plane
//   chimney: { x, z, w }          x/z fractions of footprint, w meters
//   dormer: { x, w }              roof dormer w/ window (x fraction, w meters)
//   ac: true                      AC-unit box + concrete pad on the right wall
//
// Integration notes:
//  - each instance needs addCollider(x, z, w, d) with the ROTATED footprint
//    (rot 90/270 => swap w/d) and a mapBuildings push for minimap+rain.
//  - buildHouse returns a THREE.Group anchored at ground level (y=0), front
//    wall facing +z before rotation, exactly like bldg()'s door face.
//  - budget: base house ~20-50 tris, every feature is a handful of boxes;
//    a fully-loaded cluster stays under ~450 tris (see tools/housegen/README).

/* global THREE */

var houseTexCache = {};

// hue in degrees, satMul/lightMul multiplicative; works on canvas pixel data.
// Only pixels whose CHROMA (color minus its own gray level) is close to the
// cluster's wallColor chroma are shifted — so a recolor repaints the wall and
// its shaded variants but leaves trim, garage doors and windows alone.
function houseHue2(p, q, t) {
  t = (t + 1) % 1;
  if (t < 1 / 6) return p + (q - p) * 6 * t;
  if (t < 1 / 2) return q;
  if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6;
  return p;
}
function houseShiftPixels(px, hueDeg, satMul, lightMul, baseHex) {
  var bn = parseInt((baseHex || '#c8b89a').slice(1), 16);
  var br = (bn >> 16 & 255) / 255, bg = (bn >> 8 & 255) / 255, bb = (bn & 255) / 255;
  var bav = (br + bg + bb) / 3, bcr = br - bav, bcg = bg - bav, bcb = bb - bav;
  for (var i = 0; i < px.length; i += 4) {
    var r = px[i] / 255, g = px[i + 1] / 255, b = px[i + 2] / 255;
    var av = (r + g + b) / 3;
    var dr = (r - av) - bcr, dg = (g - av) - bcg, db = (b - av) - bcb;
    var cd = Math.sqrt(dr * dr + dg * dg + db * db);
    var f = Math.min(1, Math.max(0, (0.09 - cd) / 0.045)); // 1 near wall chroma, 0 away
    if (f <= 0) continue;
    var mx = Math.max(r, g, b), mn = Math.min(r, g, b), l = (mx + mn) / 2;
    var h = 0, s = 0, d = mx - mn;
    if (d > 0.0001) {
      s = l > 0.5 ? d / (2 - mx - mn) : d / (mx + mn);
      if (mx === r) h = ((g - b) / d + (g < b ? 6 : 0)) / 6;
      else if (mx === g) h = ((b - r) / d + 2) / 6;
      else h = ((r - g) / d + 4) / 6;
    }
    var h2 = (h + (hueDeg / 360) * f + 1) % 1;
    var s2 = Math.min(1, Math.max(0, s * (1 + (satMul - 1) * f)));
    var l2 = Math.min(1, Math.max(0, l * (1 + (lightMul - 1) * f)));
    var q = l2 < 0.5 ? l2 * (1 + s2) : l2 + s2 - l2 * s2, p = 2 * l2 - q;
    px[i] = Math.round(houseHue2(p, q, h2 + 1 / 3) * 255);
    px[i + 1] = Math.round(houseHue2(p, q, h2) * 255);
    px[i + 2] = Math.round(houseHue2(p, q, h2 - 1 / 3) * 255);
  }
}

// hex '#rrggbb' -> shifted hex (for the plain-colored parts)
function houseShiftHex(hex, shift) {
  if (!shift) return hex;
  var n = parseInt(hex.slice(1), 16);
  var px = [n >> 16 & 255, n >> 8 & 255, n & 255, 255];
  houseShiftPixels(px, shift[0], shift[1], shift[2], hex);
  return '#' + ((1 << 24) + (px[0] << 16) + (px[1] << 8) + px[2]).toString(16).slice(1);
}

// data-URL -> THREE texture, optional per-instance recolor, cached
function houseTex(url, shift, repX, repY, baseHex) {
  var key = url.length + url.slice(-24) + '|' + (shift ? shift.join(',') : '') + '|' + (repX || 0) + ',' + (repY || 0);
  if (houseTexCache[key]) return houseTexCache[key];
  var cv = document.createElement('canvas'); cv.width = cv.height = 8;
  var t = new THREE.CanvasTexture(cv);
  t.magFilter = THREE.LinearFilter; t.minFilter = THREE.LinearMipmapLinearFilter;
  if (typeof MAXANISO !== 'undefined') t.anisotropy = MAXANISO;
  t.wrapS = t.wrapT = THREE.RepeatWrapping;
  if (repX) t.repeat.set(repX, repY || repX);
  var im = new Image();
  im.onload = function () {
    cv.width = im.width; cv.height = im.height;
    var g = cv.getContext('2d'); g.drawImage(im, 0, 0);
    if (shift) {
      var d = g.getImageData(0, 0, cv.width, cv.height);
      houseShiftPixels(d.data, shift[0], shift[1], shift[2], baseHex);
      g.putImageData(d, 0, 0);
    }
    // r149/WebGL2 allocates immutable texStorage at the placeholder size on
    // the first render; dispose() forces a re-allocation at the real size.
    t.dispose();
    t.needsUpdate = true;
  };
  im.src = url;
  houseTexCache[key] = t; return t;
}

// cluster: HOUSE_CLUSTERS entry; shift: colorShift or 0. Returns THREE.Group.
function buildHouse(cluster, shift) {
  var w = cluster.dims[0], d = cluster.dims[1], h = cluster.dims[2];
  var roofH = cluster.roofH || 2.6, ovh = 1.2;
  var feat = cluster.feat || {};
  var tex = cluster.tex;
  var g = new THREE.Group();
  function wallM(url) { return new THREE.MeshLambertMaterial({ map: houseTex(url, shift, 0, 0, cluster.wallColor) }); }
  function box(bw, bh, bd, mat) { return new THREE.Mesh(new THREE.BoxGeometry(bw, bh, bd), mat); }
  var frontM = wallM(tex.front);
  var sideM = wallM(tex.side);
  var backM = wallM(tex.back || tex.side);
  var plainM = new THREE.MeshLambertMaterial({ color: new THREE.Color(houseShiftHex(cluster.wallColor || '#c8b89a', shift)) });
  var trimHex = cluster.trimColor || '#ece8dd';
  var trimM = tex.trim ? new THREE.MeshLambertMaterial({ map: houseTex(tex.trim, 0, 1, 1) })
    : new THREE.MeshLambertMaterial({ color: new THREE.Color(trimHex) });
  var gableM = tex.gable ? new THREE.MeshLambertMaterial({ map: houseTex(tex.gable, 0, 1, 1) }) : plainM;
  var concM = tex.concrete ? new THREE.MeshLambertMaterial({ map: houseTex(tex.concrete, 0, 1, 1) })
    : new THREE.MeshLambertMaterial({ color: 0xb8b4ac });
  var glassM = new THREE.MeshLambertMaterial({ color: new THREE.Color(cluster.glassColor || '#2a3742') });
  var body = new THREE.Mesh(new THREE.BoxGeometry(w, h, d), [sideM, sideM, plainM, plainM, frontM, backM]);
  body.position.y = h / 2 + 0.05;
  g.add(body);

  // ---- roof (kept from v1; recolor never touches the roof) ----------------
  var roofM = new THREE.MeshLambertMaterial({
    map: houseTex(tex.roof, 0, Math.max(2, w / 5), Math.max(1, Math.round(d / 8))),
  });
  var miniRoofM = new THREE.MeshLambertMaterial({ map: houseTex(tex.roof, 0, 1, 1) });
  if (cluster.roofType === 'hip') {
    var hipG = new THREE.ConeGeometry(Math.SQRT1_2, 1, 4);
    hipG.rotateY(Math.PI / 4);
    var roof = new THREE.Mesh(hipG, roofM);
    roof.scale.set(w + ovh, roofH, d + ovh);
    roof.position.y = h + 0.05 + roofH / 2;
    g.add(roof);
  } else if (cluster.roofType === 'gable') {
    // ridge along x; two slopes + two triangular gable ends
    var hd = (d + ovh) / 2, slant = Math.sqrt(hd * hd + roofH * roofH), ang = Math.atan2(roofH, hd);
    var s1 = box(w + ovh, 0.22, slant + 0.3, roofM);
    s1.position.set(0, h + 0.05 + roofH / 2, -hd / 2); s1.rotation.x = -ang; g.add(s1);
    var s2 = box(w + ovh, 0.22, slant + 0.3, roofM);
    s2.position.set(0, h + 0.05 + roofH / 2, hd / 2); s2.rotation.x = ang; g.add(s2);
    var tri = new THREE.Shape();
    tri.moveTo(-d / 2, 0); tri.lineTo(d / 2, 0); tri.lineTo(0, roofH); tri.lineTo(-d / 2, 0);
    var triG = new THREE.ShapeGeometry(tri);
    // board-and-batten texture on the gable ends when the cluster has the
    // v2 gable tile: remap the shape's xy UVs to ~3.2m per texture repeat.
    if (tex.gable) {
      var uv = triG.attributes.uv;
      for (var ui = 0; ui < uv.count; ui++) uv.setXY(ui, (uv.getX(ui) + d / 2) / 3.2, uv.getY(ui) / 3.2);
    }
    triG.rotateY(Math.PI / 2);
    var e1 = new THREE.Mesh(triG, tex.gable ? gableM : plainM); e1.position.set(w / 2 - 0.01, h + 0.05, 0); g.add(e1);
    var e2 = new THREE.Mesh(triG, tex.gable ? gableM : plainM); e2.rotation.y = Math.PI; e2.position.set(-w / 2 + 0.01, h + 0.05, 0); g.add(e2);
  } else { // flat: small parapet lip
    var lip = box(w + 0.5, 0.5, d + 0.5, plainM);
    lip.position.y = h + 0.3; g.add(lip);
  }

  // ---- eave soffit + fascia (visible roof overhang underside) -------------
  if (feat.soffit && cluster.roofType !== 'flat') {
    var sofW = w + ovh * 0.8, sofD = d + ovh * 0.8;
    if (cluster.roofType === 'gable') sofW = w + ovh * 0.35; // gable ends have no eave
    var sof = box(sofW, 0.16, sofD, trimM);
    sof.position.y = h + 0.02;
    g.add(sof);
  }

  // ---- geometric window unit: trim surround box + darker glass box --------
  // (two boxes: from the front you read a dark pane in a light frame; from
  // the side both protrude from the wall — the itch.io reference look.)
  function windowUnit(ww, wh) {
    var u = new THREE.Group();
    var fr = box(ww + 0.26, wh + 0.26, 0.14, trimM); u.add(fr);
    var gl = box(ww, wh, 0.2, glassM); gl.position.z = 0.02; u.add(gl);
    return u;
  }
  // face: 'f' (+z), 'b' (-z), 'l' (-x), 'r' (+x); x = 0..1 along the wall
  function placeOnWall(obj, face, frac, y) {
    if (face === 'f') { obj.position.set((frac - 0.5) * w, y, d / 2); }
    else if (face === 'b') { obj.position.set((0.5 - frac) * w, y, -d / 2); obj.rotation.y = Math.PI; }
    else if (face === 'r') { obj.position.set(w / 2, y, d / 2 - frac * d); obj.rotation.y = Math.PI / 2; }
    else { obj.position.set(-w / 2, y, d / 2 - frac * d); obj.rotation.y = -Math.PI / 2; }
    g.add(obj);
  }
  if (feat.win) {
    for (var fk in feat.win) {
      var list = feat.win[fk];
      for (var wi = 0; wi < list.length; wi++) {
        var wn = list[wi];
        placeOnWall(windowUnit(wn[2], wn[3]), fk, wn[0], wn[1] + 0.05);
      }
    }
  }

  // ---- front door unit (+ porch or pier recess) ----------------------------
  if (feat.door) {
    var dw = feat.door.w || 1.1, dh = feat.door.h || 2.1, dx = (feat.door.x - 0.5) * w;
    var doorFaceM = tex.door ? new THREE.MeshLambertMaterial({ map: houseTex(tex.door, 0, 0, 0) }) : glassM;
    var surM = trimM;
    var sur = box(dw + 0.3, dh + 0.18, 0.1, surM);
    sur.position.set(dx, (dh + 0.18) / 2 + 0.05, d / 2);
    g.add(sur);
    var dbx = new THREE.Mesh(new THREE.BoxGeometry(dw, dh, 0.16),
      [trimM, trimM, trimM, trimM, doorFaceM, trimM]);
    dbx.position.set(dx, dh / 2 + 0.05, d / 2 + 0.02);
    g.add(dbx);
    var porch = feat.door.porch;
    if (porch) {
      var pd = porch.d || 1.6, pw = Math.max(dw + 1.5, porch.w || 0);
      // concrete stoop + one step
      var stoop = box(pw, 0.22, pd, concM);
      stoop.position.set(dx, 0.11, d / 2 + pd / 2); g.add(stoop);
      var step = box(pw * 0.72, 0.11, 0.42, concM);
      step.position.set(dx, 0.055, d / 2 + pd + 0.21); g.add(step);
      // porch roof: pitched shed slab, shingles on top / trim underneath
      var prRot = 0.24, prY = Math.min(h - 0.15, dh + 0.95);
      var pr = new THREE.Mesh(new THREE.BoxGeometry(pw + 0.5, 0.2, pd + 0.55),
        [trimM, trimM, miniRoofM, trimM, trimM, trimM]);
      pr.position.set(dx, prY, d / 2 + (pd + 0.2) / 2);
      pr.rotation.x = prRot;
      g.add(pr);
      // square posts under the roof's front corners
      var np = porch.posts || 2;
      var postH = prY - Math.sin(prRot) * (pd + 0.55) / 2 - 0.08 - 0.22;
      for (var pi = 0; pi < np; pi++) {
        var px = np === 1 ? dx : dx - pw / 2 + 0.22 + pi * (pw - 0.44) / (np - 1);
        var post = box(0.18, postH, 0.18, trimM);
        post.position.set(px, 0.22 + postH / 2, d / 2 + pd - 0.22);
        g.add(post);
      }
    } else if (feat.door.recess) {
      // alcove read: piers + header protrude, door stays at the wall plane
      // (piers wear the plain front-wall TEXTURE so per-instance recolors
      // shift them exactly like the wall — a plain-color material drifts)
      var p1 = box(0.3, dh + 0.2, 0.55, frontM);
      p1.position.set(dx - dw / 2 - 0.3, (dh + 0.2) / 2 + 0.05, d / 2 + 0.18); g.add(p1);
      var p2 = box(0.3, dh + 0.2, 0.55, frontM);
      p2.position.set(dx + dw / 2 + 0.3, (dh + 0.2) / 2 + 0.05, d / 2 + 0.18); g.add(p2);
      var hd2 = box(dw + 1.2, 0.35, 0.55, frontM);
      hd2.position.set(dx, dh + 0.25, d / 2 + 0.18); g.add(hd2);
      var stp = box(dw + 0.7, 0.14, 0.9, concM);
      stp.position.set(dx, 0.07, d / 2 + 0.45); g.add(stp);
    }
  }

  // ---- garage-door inset: piers + header protrude, door tile sits back ----
  if (feat.garage && tex.garage) {
    var gw = feat.garage.w || 4.8, gh = feat.garage.h || 2.3, gout = feat.garage.out || 0.4;
    var gx = (feat.garage.x - 0.5) * w;
    var garM = new THREE.MeshLambertMaterial({ map: houseTex(tex.garage, 0, 0, 0) });
    var gd = new THREE.Mesh(new THREE.BoxGeometry(gw, gh, 0.12),
      [frontM, frontM, frontM, frontM, garM, frontM]);
    gd.position.set(gx, gh / 2 + 0.05, d / 2 + 0.01);
    g.add(gd);
    // surround wears the plain front-wall texture (recolor-consistent)
    var gp1 = box(0.35, gh + 0.05, gout + 0.12, frontM);
    gp1.position.set(gx - gw / 2 - 0.17, (gh + 0.05) / 2 + 0.05, d / 2 + gout / 2); g.add(gp1);
    var gp2 = box(0.35, gh + 0.05, gout + 0.12, frontM);
    gp2.position.set(gx + gw / 2 + 0.17, (gh + 0.05) / 2 + 0.05, d / 2 + gout / 2); g.add(gp2);
    var gh3 = box(gw + 0.7, 0.42, gout + 0.12, frontM);
    gh3.position.set(gx, gh + 0.26, d / 2 + gout / 2); g.add(gh3);
    // concrete apron in front of the door
    var apron = box(gw + 0.4, 0.08, 1.6, concM);
    apron.position.set(gx, 0.04, d / 2 + 0.8); g.add(apron);
  }

  // ---- chimney -------------------------------------------------------------
  if (feat.chimney) {
    var cw = feat.chimney.w || 0.7;
    var chX = (feat.chimney.x - 0.5) * w, chZ = (feat.chimney.z - 0.5) * d;
    var chTop = h + roofH + 0.45;
    var ch = box(cw, chTop - h + 1.2, cw * 0.8, plainM);
    ch.position.set(chX, (chTop + h - 1.2) / 2, chZ); g.add(ch);
    var cap = box(cw + 0.18, 0.16, cw * 0.8 + 0.18, trimM);
    cap.position.set(chX, chTop + 0.08, chZ); g.add(cap);
  }

  // ---- dormer on the front roof slope (two-story / gable clusters) --------
  if (feat.dormer && cluster.roofType !== 'flat') {
    var dmW = feat.dormer.w || 2.1, dmH = 1.7, dmD = 1.5;
    var dmX = ((feat.dormer.x || 0.5) - 0.5) * w;
    var hd3 = (d + ovh) / 2;
    var zf = hd3 * 0.5;                       // front face z on the slope
    var yb = h + 0.3;                         // dormer base height
    var dm = new THREE.Mesh(new THREE.BoxGeometry(dmW, dmH, dmD),
      [gableM, gableM, gableM, gableM, gableM, gableM]);
    dm.position.set(dmX, yb + dmH / 2, zf - dmD / 2);
    g.add(dm);
    var dwin = windowUnit(dmW - 1.0, dmH - 0.85);
    dwin.position.set(dmX, yb + dmH / 2 - 0.08, zf);
    g.add(dwin);
    // little gable roof: two slabs, ridge running front-to-back (z)
    var drRise = 0.42;
    var dra = Math.atan2(drRise, dmW / 2);
    var drs = Math.sqrt(dmW * dmW / 4 + drRise * drRise) + 0.3;
    var dr1 = box(drs, 0.1, dmD + 0.5, miniRoofM);
    dr1.position.set(dmX - dmW / 4, yb + dmH + 0.1, zf - dmD / 2);
    dr1.rotation.z = dra; g.add(dr1);
    var dr2 = box(drs, 0.1, dmD + 0.5, miniRoofM);
    dr2.position.set(dmX + dmW / 4, yb + dmH + 0.1, zf - dmD / 2);
    dr2.rotation.z = -dra; g.add(dr2);
  }

  // ---- generic extra boxes: balconies, parapet caps, bays, canopies -------
  // feat.boxes: [ [mat, x, y, z, bw, bh, bd], ... ] — box centered at
  // (x, y, z) in house space (meters; +z = front). mat: 'trim'|'wall'|
  // 'conc'|'gable'|'glass'|'roof'|'door'|'garage'. 'wall' wears the front
  // texture so recolors track it (same rule as garage piers).
  if (feat.boxes) {
    var bMats = { trim: trimM, wall: frontM, conc: concM, gable: gableM, glass: glassM, roof: miniRoofM };
    if (tex.door) bMats.door = new THREE.MeshLambertMaterial({ map: houseTex(tex.door, 0, 0, 0) });
    if (tex.garage) bMats.garage = new THREE.MeshLambertMaterial({ map: houseTex(tex.garage, 0, 0, 0) });
    for (var bxi = 0; bxi < feat.boxes.length; bxi++) {
      var bspec = feat.boxes[bxi];
      var bmesh = box(bspec[4], bspec[5], bspec[6], bMats[bspec[0]] || trimM);
      bmesh.position.set(bspec[1], bspec[2], bspec[3]);
      g.add(bmesh);
    }
  }

  // ---- AC unit + pad on the right (+x) wall, street-prop-style clutter ----
  if (feat.ac) {
    var pad = box(1.1, 0.1, 0.6, concM);
    pad.position.set(w / 2 + 0.35, 0.05, d * 0.12); g.add(pad);
    var acm = new THREE.MeshLambertMaterial({ color: 0x9aa0a2 });
    var ac = box(0.75, 0.62, 0.42, acm);
    ac.position.set(w / 2 + 0.33, 0.41, d * 0.12); g.add(ac);
  }

  return g;
}

// Place every HOUSE_INSTANCES entry. addTo(scene)-style helper; in game.js
// call once from the city-layout section (plus addCollider/mapBuildings per
// instance — see integration notes above).
function buildHouseInstances(scene) {
  if (typeof HOUSE_CLUSTERS === 'undefined') return;
  for (var i = 0; i < HOUSE_INSTANCES.length; i++) {
    var inst = HOUSE_INSTANCES[i];
    var cl = HOUSE_CLUSTERS[inst[0]];
    if (!cl) continue;
    var hg = buildHouse(cl, inst[4] || 0);
    hg.position.set(inst[1], 0, inst[2]);
    hg.rotation.y = inst[3] * Math.PI / 180;
    scene.add(hg);
  }
}
