// runtime_buildhouse.js — game-side house builder for AI-generated house
// clusters (tools/housegen). Written for game.js (ES5, three.js r149 UMD).
// NOT yet wired into the game: the integration agent should paste/adapt this
// into game.js near the other building helpers (bldg/shop/stripMall) and load
// houses.js (var HOUSE_CLUSTERS / HOUSE_INSTANCES) before game.js like
// meshychars.js is loaded.
//
// Data contract (houses.js, generated by tools/housegen/mkhouses.js):
//   var HOUSE_CLUSTERS = { id: { tex: {front,side,back,roof},  // JPEG data-URLs
//                                dims: [w,d,h], roofType: 'hip'|'gable'|'flat',
//                                roofH, wallColor } };
//   var HOUSE_INSTANCES = [ [clusterId, x, z, rotDeg, colorShift], ... ];
//   colorShift: 0 (none) or [hueDeg, satMul, lightMul] — cheap per-instance
//   recolor of the SAME cluster textures (one gray house becomes tan/sage).
//
// Integration notes:
//  - each instance needs addCollider(x, z, w, d) with the ROTATED footprint
//    (rot 90/270 => swap w/d) and a mapBuildings push for minimap+rain.
//  - buildHouse returns a THREE.Group anchored at ground level (y=0), front
//    wall facing +z before rotation, exactly like bldg()'s door face.

/* global THREE */

var houseTexCache = {};

// hue in degrees, satMul/lightMul multiplicative; works on canvas pixel data
function houseShiftPixels(px, hueDeg, satMul, lightMul) {
  for (var i = 0; i < px.length; i += 4) {
    var r = px[i] / 255, g = px[i + 1] / 255, b = px[i + 2] / 255;
    var mx = Math.max(r, g, b), mn = Math.min(r, g, b), l = (mx + mn) / 2;
    var h = 0, s = 0, d = mx - mn;
    if (d > 0.0001) {
      s = l > 0.5 ? d / (2 - mx - mn) : d / (mx + mn);
      if (mx === r) h = ((g - b) / d + (g < b ? 6 : 0)) / 6;
      else if (mx === g) h = ((b - r) / d + 2) / 6;
      else h = ((r - g) / d + 4) / 6;
    }
    h = (h + hueDeg / 360 + 1) % 1;
    s = Math.min(1, Math.max(0, s * satMul));
    l = Math.min(1, Math.max(0, l * lightMul));
    var q = l < 0.5 ? l * (1 + s) : l + s - l * s, p = 2 * l - q;
    function hue2(t) {
      t = (t + 1) % 1;
      if (t < 1 / 6) return p + (q - p) * 6 * t;
      if (t < 1 / 2) return q;
      if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6;
      return p;
    }
    px[i] = Math.round(hue2(h + 1 / 3) * 255);
    px[i + 1] = Math.round(hue2(h) * 255);
    px[i + 2] = Math.round(hue2(h - 1 / 3) * 255);
  }
}

// hex '#rrggbb' -> shifted hex (for the plain-colored gable ends)
function houseShiftHex(hex, shift) {
  if (!shift) return hex;
  var n = parseInt(hex.slice(1), 16);
  var px = [n >> 16 & 255, n >> 8 & 255, n & 255, 255];
  houseShiftPixels(px, shift[0], shift[1], shift[2]);
  return '#' + ((1 << 24) + (px[0] << 16) + (px[1] << 8) + px[2]).toString(16).slice(1);
}

// data-URL -> THREE texture, optional per-instance recolor, cached
function houseTex(url, shift, repX, repY) {
  var key = url.length + url.slice(-24) + '|' + (shift ? shift.join(',') : '') + '|' + (repX || 0) + ',' + (repY || 0);
  if (houseTexCache[key]) return houseTexCache[key];
  var cv = document.createElement('canvas'); cv.width = cv.height = 8;
  var t = new THREE.CanvasTexture(cv);
  t.magFilter = THREE.LinearFilter; t.minFilter = THREE.LinearMipmapLinearFilter;
  if (typeof MAXANISO !== 'undefined') t.anisotropy = MAXANISO;
  t.wrapS = t.wrapT = THREE.RepeatWrapping;
  if (repX) t.repeat.set(repX, repY || repX);
  var im = new Image();
  im.onload = function () {
    cv.width = im.width; cv.height = im.height;
    var g = cv.getContext('2d'); g.drawImage(im, 0, 0);
    if (shift) {
      var d = g.getImageData(0, 0, cv.width, cv.height);
      houseShiftPixels(d.data, shift[0], shift[1], shift[2]);
      g.putImageData(d, 0, 0);
    }
    t.needsUpdate = true;
  };
  im.src = url;
  houseTexCache[key] = t; return t;
}

// cluster: HOUSE_CLUSTERS entry; shift: colorShift or 0. Returns THREE.Group.
function buildHouse(cluster, shift) {
  var w = cluster.dims[0], d = cluster.dims[1], h = cluster.dims[2];
  var roofH = cluster.roofH || 2.6, ovh = 1.2;
  var g = new THREE.Group();
  function wallM(url) { return new THREE.MeshLambertMaterial({ map: houseTex(url, shift) }); }
  var frontM = wallM(cluster.tex.front);
  var sideM = wallM(cluster.tex.side);
  var backM = wallM(cluster.tex.back || cluster.tex.side);
  var plainM = new THREE.MeshLambertMaterial({ color: new THREE.Color(houseShiftHex(cluster.wallColor || '#c8b89a', shift)) });
  var body = new THREE.Mesh(new THREE.BoxGeometry(w, h, d), [sideM, sideM, plainM, plainM, frontM, backM]);
  body.position.y = h / 2 + 0.05;
  g.add(body);

  var roofM = new THREE.MeshLambertMaterial({
    map: houseTex(cluster.tex.roof, shift, Math.max(2, w / 5), Math.max(1, Math.round(d / 8))),
  });
  if (cluster.roofType === 'hip') {
    var hipG = new THREE.ConeGeometry(Math.SQRT1_2, 1, 4);
    hipG.rotateY(Math.PI / 4);
    var roof = new THREE.Mesh(hipG, roofM);
    roof.scale.set(w + ovh, roofH, d + ovh);
    roof.position.y = h + 0.05 + roofH / 2;
    g.add(roof);
  } else if (cluster.roofType === 'gable') {
    // ridge along x; two slopes + two triangular gable ends (plain wall color)
    var hd = (d + ovh) / 2, slant = Math.sqrt(hd * hd + roofH * roofH), ang = Math.atan2(roofH, hd);
    var s1 = new THREE.Mesh(new THREE.BoxGeometry(w + ovh, 0.22, slant + 0.3), roofM);
    s1.position.set(0, h + 0.05 + roofH / 2, -hd / 2); s1.rotation.x = ang; g.add(s1);
    var s2 = new THREE.Mesh(new THREE.BoxGeometry(w + ovh, 0.22, slant + 0.3), roofM);
    s2.position.set(0, h + 0.05 + roofH / 2, hd / 2); s2.rotation.x = -ang; g.add(s2);
    var tri = new THREE.Shape();
    tri.moveTo(-d / 2, 0); tri.lineTo(d / 2, 0); tri.lineTo(0, roofH); tri.lineTo(-d / 2, 0);
    var triG = new THREE.ShapeGeometry(tri); triG.rotateY(Math.PI / 2);
    var e1 = new THREE.Mesh(triG, plainM); e1.position.set(w / 2 - 0.01, h + 0.05, 0); g.add(e1);
    var e2 = new THREE.Mesh(triG, plainM); e2.rotation.y = Math.PI; e2.position.set(-w / 2 + 0.01, h + 0.05, 0); g.add(e2);
  } else { // flat: small parapet lip
    var lip = new THREE.Mesh(new THREE.BoxGeometry(w + 0.5, 0.5, d + 0.5), plainM);
    lip.position.y = h + 0.3; g.add(lip);
  }
  return g;
}

// Place every HOUSE_INSTANCES entry. addTo(scene)-style helper; in game.js
// call once from the city-layout section (plus addCollider/mapBuildings per
// instance — see integration notes above).
function buildHouseInstances(scene) {
  if (typeof HOUSE_CLUSTERS === 'undefined') return;
  for (var i = 0; i < HOUSE_INSTANCES.length; i++) {
    var inst = HOUSE_INSTANCES[i];
    var cl = HOUSE_CLUSTERS[inst[0]];
    if (!cl) continue;
    var hg = buildHouse(cl, inst[4] || 0);
    hg.position.set(inst[1], 0, inst[2]);
    hg.rotation.y = inst[3] * Math.PI / 180;
    scene.add(hg);
  }
}
