// SFX pipeline — baker. Wraps the sliced WAVs into soundfx.js: a single
// ES5 global `SFX_PACK` of data-URL arrays, loaded by index.html before
// game.js (typeof-guarded there — the game runs fine without it).
//   Run: node tools/sfxgen/bake.js
var fs = require('fs');
var path = require('path');

var SCRATCH = process.env.SFX_SCRATCH ||
  '/tmp/claude-0/-home-user-westchase-fps/efaef73e-76aa-5d75-8d6c-935e41bd5d2d/scratchpad/sfx';
var CUT = path.join(SCRATCH, 'cut');
var OUT = path.join(__dirname, '..', '..', 'soundfx.js');

// pack key -> slice basenames (every <name>_N.wav found is a round-robin variant)
var PACK = {
  pistol: 'pistol', smg: 'smg', rifle: 'rifle', auto: 'ak',
  rocketfire: 'rocketfire', boom: 'boom', crash: 'crash', glass: 'glass',
  punch: 'punch', cash: 'cash', eat: 'eat', horn: 'horn',
  ricochet: 'ricochet', cardoor: 'cardoor',
  step_concrete: 'step_concrete', step_grass: 'step_grass',
  step_water: 'step_water', step_wood: 'step_wood',
  eng_idle_a: 'eng_idle_a', eng_high_a: 'eng_high_a',
  eng_idle_b: 'eng_idle_b', eng_high_b: 'eng_high_b',
  eng_idle_c: 'eng_idle_c', eng_high_c: 'eng_high_c',
  eng_idle_d: 'eng_idle_d', eng_high_d: 'eng_high_d'
};

// flee screams (screamgen.js, psxified 8-bit/11025): trim lead/trail silence
// so the scream hits the instant the flee starts, then group by sex/kid key.
var SCREAMS = path.join(SCRATCH, 'screams');
function trimScream(buf) {
  // psxify output is a fixed 44-byte header + 8-bit unsigned mono data
  var rate = buf.readUInt32LE(24), d = buf.slice(44);
  var s = 0, e = d.length - 1, TH = 10;   // |sample-128| > 10 = signal
  while (s < d.length && Math.abs(d[s] - 128) <= TH) s++;
  while (e > s && Math.abs(d[e] - 128) <= TH) e--;
  s = Math.max(0, s - Math.round(rate * 0.03));
  e = Math.min(d.length - 1, e + Math.round(rate * 0.08));
  var n = e - s + 1;
  var o = Buffer.alloc(44 + n);
  buf.copy(o, 0, 0, 44);
  d.copy(o, 44, s, e + 1);
  o.writeUInt32LE(36 + n, 4); o.writeUInt32LE(n, 40);
  return o;
}

var out = [];
out.push('// soundfx.js — Lyria-3-generated SFX pack (v1 sound overhaul).');
out.push('// GENERATED by tools/sfxgen/bake.js — do not hand-edit. Source clips were');
out.push('// produced OFFLINE by tools/sfxgen/gen.js (lyria-3-clip-preview), sliced +');
out.push('// normalized by slice.js. 16-bit mono WAV data-URLs; game.js decodes them');
out.push('// once into AudioBuffers (sfxPack*) and falls back to the old synth when');
out.push('// this file or an entry is absent. Multiple entries per key = round-robin');
out.push('// variants. Never reference external URLs; file:// must keep working.');
out.push('var SFX_PACK = {');
var keys = Object.keys(PACK), total = 0;
keys.forEach(function (k, ki) {
  var urls = [];
  for (var n = 0; n < 12; n++) {
    var f = path.join(CUT, PACK[k] + '_' + n + '.wav');
    if (!fs.existsSync(f)) break;
    var b = fs.readFileSync(f);
    total += b.length;
    urls.push("'data:audio/wav;base64," + b.toString('base64') + "'");
  }
  if (!urls.length) { console.error('WARN: no slices for ' + k); return; }
  out.push('  ' + k + ': [' + urls.join(',') + '],');
});
['scream_m', 'scream_f', 'scream_kid'].forEach(function (k, ki, alist) {
  var urls = [];
  for (var n = 0; n < 8; n++) {
    var f = path.join(SCREAMS, k + '_' + n + '.wav');
    if (!fs.existsSync(f)) break;
    var b = trimScream(fs.readFileSync(f));
    total += b.length;
    urls.push("'data:audio/wav;base64," + b.toString('base64') + "'");
  }
  if (!urls.length) { console.error('WARN: no screams for ' + k); return; }
  out.push('  ' + k + ': [' + urls.join(',') + ']' + (ki < alist.length - 1 ? ',' : ''));
});
out.push('};');
fs.writeFileSync(OUT, out.join('\n') + '\n');
console.log('wrote ' + OUT + ' (' + fs.statSync(OUT).size + ' bytes, ' + keys.length + ' keys, wav bytes=' + total + ')');
