// quest_items.js — quest inventory-icon catalog for Westchase FPS.
// 36 icons across 4 grids of 9 (3x3 magenta-key tiling, per itemgen/ITEMICONS.md).
// Covers the ~30 quest items in quest_assets.json plus a few flavor/heist items
// (filled to 4 clean 9-cell grids). Each entry drives the gpt-image-1 cell
// prompt (`p`) AND the QUEST_ITEM_DEFS row.
//   quest: which quest the item belongs to.  use: reward|clue|key|tool|thread|entry.
//   notes: quest-mechanic use (from the manifest).
'use strict';

const GRIDS = [
  // ---- Grid 0: documents / paper / cards --------------------------------
  [
    { id:'eviction_notice', name:'Eviction Notice', quest:'q1_dismember', use:'thread',
      notes:'first Countryway-seal thread tile (recurs q3/q8)',
      p:'a torn cream paper letter with a large blood-red wax seal at the bottom, stern black text lines, one corner ripped off' },
    { id:'welcome_packet', name:'Association Welcome Packet', quest:'q3_redhouse', use:'thread',
      notes:'eviction-seal thread tile',
      p:'a faded 1980s manila folder packet stamped with a round embossed HOA seal, dog-eared curling corners, retro' },
    { id:'assoc_ledger', name:'Association Ledger', quest:'q4_heist', use:'thread',
      notes:'names Thorne + the board -> q10',
      p:'a thick closed black leather accounts ledger book with a small gold circular seal embossed on the cover' },
    { id:'caretaker_ledger', name:"Caretaker's Ledger", quest:'q3_redhouse', use:'clue',
      notes:'"reclaimed by the lake" thread reveal',
      p:'an old worn brown leather ledger book lying open, two yellowed pages covered in faint handwritten names' },
    { id:'dossier', name:'Contract Dossier', quest:'q8_cleaners', use:'clue',
      notes:'names each Cleaners target',
      p:'a manila dossier folder with a small black-and-white photo clipped on and a paperclip poking out the top' },
    { id:'seating_chart', name:'Scratched Seating Chart', quest:'q1_dismember', use:'clue',
      notes:'points to the killer',
      p:'a smudged hand-drawn dinner seating diagram on paper, an oval table ringed with names, one name scratched out in red' },
    { id:'marks_note', name:'Marks Corkboard Note', quest:'q5_siren', use:'thread',
      notes:'"flagged for the board" Pact thread tile',
      p:'a white index card pinned with a single red push-pin, hurried handwritten text, one corner curled up' },
    { id:'black_card', name:'Black Calling Card', quest:'q8_cleaners', use:'entry',
      notes:'Cleaners recruitment trigger item',
      p:'a sleek matte-black business calling card with a small embossed silver circular seal centered on it' },
    { id:'lake_photo', name:'Photo of the Lights', quest:'q2_watching', use:'thread',
      notes:'UFO / lake thread tile',
      p:'a square instant polaroid photo with a white border showing an eerie glowing green light hovering over dark water' },
  ],
  // ---- Grid 1: keys / tools ---------------------------------------------
  [
    { id:'loupe', name:"Detective's Loupe", quest:'q1_dismember', use:'reward',
      notes:'REWARD capability: highlight clues + reveal trapped/false-bottom containers',
      p:'a brass jeweler\'s magnifying loupe with a round glass lens that has a visible crack across it, ornate handle' },
    { id:'lockpick_set', name:'Lockpick Set', quest:'q4_heist', use:'reward',
      notes:'REWARD capability: silently open locked doors/containers/ATMs/cars',
      p:'an open brown leather tool roll holding a row of slim silver lockpicks and one L-shaped tension wrench' },
    { id:'elevator_key', name:'Brass Elevator Key', quest:'q3_redhouse', use:'key',
      notes:'board-room lift key',
      p:'an ornate antique brass key with an elaborate looping bow and a long barrel with a single tooth' },
    { id:'etched_lake_key', name:'Etched Lake Key', quest:'q4_heist', use:'key',
      notes:'q10 sub-lake door key 1/3',
      p:'a heavy dark metal key etched all over with wavy water-ripple glyphs, faint cyan glow in the carved grooves' },
    { id:'guard_key', name:"Guard's Key", quest:'q4_heist', use:'key',
      notes:'vault access key 1',
      p:'a small metal keyring holding two silver keys and a round security-badge fob' },
    { id:'manager_key', name:"Manager's Key", quest:'q4_heist', use:'key',
      notes:'vault access key 2 (from false-bottom dumpster)',
      p:'a single small brass office door key with a plain square head' },
    { id:'timer_key', name:'Timer Key', quest:'q4_heist', use:'key',
      notes:'vault access key 3 (from roof stash)',
      p:'a small red plastic keyed control switch with a short brass key inserted in it' },
    { id:'matchbook', name:"Ghost Child's Matchbook", quest:'q3_redhouse', use:'tool',
      notes:'lights the Spirit Lantern',
      p:'a small closed cardboard matchbook with a worn cover and one paper match sticking out the top' },
    { id:'binoculars', name:"Wendell's Binoculars", quest:'q2_watching', use:'tool',
      notes:'tailing / spotting',
      p:'a pair of battered black field binoculars, twin barrels, a frayed neck strap looped beside them' },
  ],
  // ---- Grid 2: tech / weapons / reward gadgets --------------------------
  [
    { id:'scanner', name:'Police Scanner', quest:'q2_watching', use:'reward',
      notes:'REWARD capability: dispatch audio + patrol/spawn minimap marks',
      p:'a cracked black handheld police scanner radio with a bent silver antenna and a small glowing green display' },
    { id:'birdhouse_cam', name:'Birdhouse Camera', quest:'q2_watching', use:'clue',
      notes:'proof the watching is real',
      p:'a little wooden birdhouse with a round entrance hole, a small black camera lens poking out and a tiny red light' },
    { id:'neon_blaster', name:'Neon Blaster', quest:'q6_arcade', use:'reward',
      notes:'REWARD weapon skin (paired with 8-Bit Reflexes)',
      p:'a glowing neon-wireframe raygun pistol, bright cyan and magenta glowing edges over a dark body, retro sci-fi blaster' },
    { id:'silenced_pistol', name:'Silenced Pistol', quest:'q8_cleaners', use:'reward',
      notes:'REWARD weapon (paired with Ghost)',
      p:'a matte-black semi-automatic pistol with an oversized cylindrical suppressor screwed onto the barrel, side view' },
    { id:'scorched_rpg', name:'Scorched Earth RPG', quest:'q10_beneath', use:'reward',
      notes:'REWARD (Burn ending): unique rocket-launcher skin',
      p:'a battle-scarred rocket launcher tube, olive-green paint blackened and scorched and dented, a warhead loaded at the muzzle' },
    { id:'cartridge', name:'WESTCHASE Cartridge', quest:'q6_arcade', use:'entry',
      notes:'arcade entry item; crumbles to lake sand',
      p:'a blank grey retro video-game cartridge with no label, chunky plastic, a trickle of glowing sand leaking from one edge' },
    { id:'reflexes', name:'8-Bit Reflexes', quest:'q6_arcade', use:'reward',
      notes:'REWARD capability: ADS bullet-time',
      p:'a bright pink pixel-art heart power-up, blocky chunky 8-bit pixels with a small white pixel shine' },
    { id:'dog_whistle', name:'Dog Whistle', quest:'q9_biscuit', use:'reward',
      notes:'REWARD capability: summon Biscuit companion',
      p:'a small shiny brass dog whistle threaded onto a red fabric collar with a round metal name tag' },
    { id:'alien_keycard', name:'Alien Keycard', quest:'q9_biscuit', use:'key',
      notes:'q10 sub-lake door key 3/3',
      p:'a glowing angular keycard fragment of unearthly iridescent blue-green metal with strange etched circuitry' },
  ],
  // ---- Grid 3: reward gear / clues / keys -------------------------------
  [
    { id:'lantern', name:'Spirit Lantern', quest:'q3_redhouse', use:'reward',
      notes:'REWARD capability: dark-vision, reveal hidden doors, part apparitions',
      p:'an antique brass oil lantern with a glass chamber holding an eerie green flame and a carry ring on top' },
    { id:'almond_vial', name:'Bitter Almond Vial', quest:'q1_dismember', use:'clue',
      notes:'murder-weapon clue',
      p:'a tiny corked brown glass poison vial half full of dark liquid, a small white skull label' },
    { id:'bait_car_keys', name:'Bait Car Keys + Slim Jim', quest:'q5_siren', use:'reward',
      notes:'REWARD: unique fast car + instant hotwire',
      p:'a car key on a ring with a red heart-shaped charm fob, crossed over a flat metal slim-jim lockout tool' },
    { id:'sprint_shoes', name:"Vlad's Blessed Sneakers", quest:'q7_legday', use:'reward',
      notes:'REWARD capability: faster run + double jump',
      p:'a pair of chunky white and neon-green cross-training sneakers with thick soles, glowing with a faint energy aura' },
    { id:'protein_shaker', name:"Cardio-Boy's Protein", quest:'q7_legday', use:'clue',
      notes:'absurd fetch item',
      p:'a translucent plastic gym protein shaker bottle with a bright-blue lid and a frothy beige shake sloshing inside' },
    { id:'board_signet', name:'The Board Signet', quest:'q10_beneath', use:'reward',
      notes:'REWARD (Inherit ending): run Westchase town-wide perk',
      p:'a heavy gold signet ring with a flat round face engraved with an ornate Countryway crest seal' },
    { id:'whistleblower_perk', name:'The Whistleblower', quest:'q10_beneath', use:'reward',
      notes:'REWARD (Expose ending): cop leniency + hero prices',
      p:'a laminated press badge on a lanyard beside a broken red wax seal snapped cleanly in two' },
    { id:'ghost_perk', name:'Ghost', quest:'q8_cleaners', use:'reward',
      notes:'REWARD capability: stealth kills don\'t raise wanted + dealer discount',
      p:'a plain black calling card with a faint pale-white ghostly silhouette of a figure printed on it' },
    { id:'tunnel_fragment', name:'Tunnel Map Fragment', quest:'q7_legday', use:'key',
      notes:'q10 sub-lake door key 2/3',
      p:'a torn scrap of a blue architectural blueprint showing part of a tunnel cross-section diagram, ragged burnt edges' },
  ],
];

module.exports = { GRIDS };
